name: build_winner_app_desktop
version: 0.1.2
publish_to: none
description: 执行打包的桌面版本
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  tdesign_flutter: ^0.1.6
  dio: ^5.7.0
  flutter_smart_dialog: ^4.9.8+3
  darty_json_safe: ^1.0.3
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
